services:
  sqldata:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql

  order-microservice:
    env_file:
      - src/order-microservice/.env
    ports:
      - "4000:8000"
    build:
      dockerfile: ./src/order-microservice/Dockerfile
      context: .
    command: CompileDaemon --build="go build main.go" --command=./main
    volumes:
      - ./src/order-microservice:/app
    depends_on:
      - sqldata

volumes:
  postgres:
